version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'java-postgres-student_project'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_project
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-boot-network

  springboot-app:
    image: 'spring-boot:1.0'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network

volumes:
  postgres_data:

networks:
  spring-boot-network:
    driver: bridge